name: Sync Wiki

on:
  push:
    branches:
      - main

jobs:
  sync-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Checkout wiki repo
        uses: actions/checkout@v4
        with:
          repository: Adlinke/sap-international-development.wiki
          path: wiki
          token: ${{ secrets.PAT_TOKEN }}   # Use a Personal Access Token stored in repo secrets

      - name: Sync wiki content
        run: |
          cp -r *.md wiki/ || true
          cp -r docs wiki/docs || true
          cp -r projects wiki/projects || true
          cp -r samples wiki/samples || true

      - name: Commit & Push wiki
        run: |
          cd wiki
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync wiki content from main repo" || echo "No changes to commit"
          git push origin master   # Use master if wiki repo doesn’t have main
